name = "Play House"
author = "Scott & Alex Horsley"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4fddf43ebbd8610b767acedb0864d5ab2a0718a65d68ee2f37c08dbdfcf033a"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
